import { Tool } from "@/types/tool.types";

export type ToolMeta = Omit<Tool, "component">;

export const tools: ToolMeta[] = [
  {
    name: "Image Compressor",
    slug: "image-compressor",
    description: "Reduce image file size without losing quality.",
    category: "Image Tools",
    icon: "ðŸ—œï¸",
  },
  {
    name: "Image Resizer",
    slug: "image-resizer",
    description: "Resize image dimensions easily.",
    category: "Image Tools",
    icon: "â†”ï¸",
  },
  {
    name: "PNG to JPG Converter",
    slug: "png-jpg-converter",
    description: "Convert PNG images to JPG format.",
    category: "Image Tools",
    icon: "ðŸ”„",
  },
  {
    name: "WebP Converter",
    slug: "webp-converter",
    description: "Convert images to WebP format.",
    category: "Image Tools",
    icon: "ðŸŒ",
  },
  {
    name: "Watermark Image",
    slug: "watermark-image",
    description: "Add watermark to images.",
    category: "Image Tools",
    icon: "ðŸ’§",
  },
  {
    name: "Merge PDF",
    slug: "merge-pdf",
    description: "Combine multiple PDFs into one file.",
    category: "Document Tools",
    icon: "ðŸ”—",
  },
  {
    name: "Split PDF",
    slug: "split-pdf",
    description: "Split PDF into separate pages.",
    category: "Document Tools",
    icon: "âœ‚ï¸",
  },
  {
    name: "Rotate PDF",
    slug: "rotate-pdf",
    description: "Rotate PDF pages.",
    category: "Document Tools",
    icon: "ðŸ”ƒ",
  },
  {
    name: "Protect PDF",
    slug: "protect-pdf",
    description: "Add password to PDF.",
    category: "Document Tools",
    icon: "ðŸ”’",
  },
  {
    name: "Unlock PDF",
    slug: "unlock-pdf",
    description: "Remove password from PDF.",
    category: "Document Tools",
    icon: "ðŸ”“",
  },
  {
    name: "PDF to Word",
    slug: "pdf-to-word",
    description: "Convert PDF files to editable Word documents.",
    category: "Document Tools",
    icon: "ðŸ“",
  },
  {
    name: "Word to PDF",
    slug: "word-to-pdf",
    description: "Convert Word documents into PDF format.",
    category: "Document Tools",
    icon: "ðŸ“‘",
  },
  {
    name: "PDF to Excel",
    slug: "pdf-to-excel",
    description: "Extract tables from PDF into Excel format.",
    category: "Document Tools",
    icon: "ðŸ“Š",
  },
  {
    name: "Excel to PDF",
    slug: "excel-to-pdf",
    description: "Convert Excel spreadsheets into PDF files.",
    category: "Document Tools",
    icon: "ðŸ“‹",
  },
  {
    name: "PDF to PowerPoint",
    slug: "pdf-to-powerpoint",
    description: "Convert PDF files into PowerPoint slides.",
    category: "Document Tools",
    icon: "ðŸ“½ï¸",
  },
  {
    name: "PowerPoint to PDF",
    slug: "powerpoint-to-pdf",
    description: "Convert PowerPoint presentations into PDF.",
    category: "Document Tools",
    icon: "ðŸŽ¯",
  },
  {
    name: "PDF to TXT",
    slug: "pdf-to-txt",
    description: "Extract text from PDF files.",
    category: "Document Tools",
    icon: "ðŸ“ƒ",
  },
  {
    name: "TXT to PDF",
    slug: "txt-to-pdf",
    description: "Convert plain text files into PDF format.",
    category: "Document Tools",
    icon: "ðŸ“„",
  },
  {
    name: "Word to HTML",
    slug: "word-to-html",
    description: "Convert Word documents into HTML code.",
    category: "Document Tools",
    icon: "ðŸŒ",
  },
  {
    name: "JSON Formatter",
    slug: "json-formatter",
    description: "Beautify and format JSON.",
    category: "Developer Tools",
    icon: "ðŸ”§",
  },
  {
    name: "QR Generator",
    slug: "qr-generator",
    description: "Generate QR code instantly.",
    category: "Developer Tools",
    icon: "â¬›",
  },
  {
    name: "Base64 Tool",
    slug: "base64-tool",
    description: "Encode and decode Base64.",
    category: "Developer Tools",
    icon: "ðŸ”",
  },
  {
    name: "GST Calculator",
    slug: "gst-calculator",
    description: "Calculate GST easily.",
    category: "Calculators",
    icon: "ðŸ’°",
  },
  {
    name: "EMI Calculator",
    slug: "emi-calculator",
    description: "Calculate EMI quickly.",
    category: "Calculators",
    icon: "ðŸ¦",
  },
  {
    name: "Age Calculator",
    slug: "age-calculator",
    description: "Calculate your age.",
    category: "Calculators",
    icon: "ðŸŽ‚",
  },
  {
    name: "Percentage Calculator",
    slug: "percentage-calculator",
    description: "Calculate percentage instantly.",
    category: "Calculators",
    icon: "ðŸ“Š",
  },
  {
    name: "SIP Calculator",
    slug: "sip-calculator",
    description: "Calculate SIP investment growth.",
    category: "Calculators",
    icon: "ðŸ“ˆ",
  },
];

export const getToolBySlug = (slug: string) =>
  tools.find((tool) => tool.slug === slug);

export const categories = [...new Set(tools.map((tool) => tool.category))];
