import { Tool } from "@/types/tool.types";

export type ToolMeta = Omit<Tool, "component">;

export const tools: ToolMeta[] = [
  {
    name: "Image Compressor",
    slug: "image-compressor",
    description: "Reduce image file size without losing quality.",
    category: "Image Tools",
    icon: "🖼️",
  },
  {
    name: "Image Resizer",
    slug: "image-resizer",
    description: "Resize image dimensions easily.",
    category: "Image Tools",
    icon: "↔️",
  },
  {
    name: "PNG to JPG Converter",
    slug: "png-jpg-converter",
    description: "Convert PNG images to JPG format.",
    category: "Image Tools",
    icon: "🔄",
  },
  {
    name: "WebP Converter",
    slug: "webp-converter",
    description: "Convert images to WebP format.",
    category: "Image Tools",
    icon: "🌐",
  },
  {
    name: "Watermark Image",
    slug: "watermark-image",
    description: "Add watermark to images.",
    category: "Image Tools",
    icon: "💧",
  },
  {
    name: "Image Background Blur",
    slug: "image-background-blur",
    description: "Blur the background of portrait or product images.",
    category: "Image Tools",
    icon: "🌫️",
  },
  {
    name: "Image Sharpen Tool",
    slug: "image-sharpen-tool",
    description: "Sharpen soft images and improve edge clarity.",
    category: "Image Tools",
    icon: "✨",
  },
  {
    name: "Image Noise Reduction",
    slug: "image-noise-reduction",
    description: "Reduce grain and digital noise in photos.",
    category: "Image Tools",
    icon: "🪄",
  },
  {
    name: "Cartoon Effect Generator",
    slug: "cartoon-effect-generator",
    description: "Turn photos into cartoon-style artwork.",
    category: "Image Tools",
    icon: "🎨",
  },
  {
    name: "Sketch Effect Generator",
    slug: "sketch-effect-generator",
    description: "Convert photos into pencil or line-art sketches.",
    category: "Image Tools",
    icon: "✏️",
  },
  {
    name: "Background Remover",
    slug: "background-remover",
    description: "Remove image backgrounds for cleaner cutouts.",
    category: "Image Tools",
    icon: "🧼",
  },
  {
    name: "Passport Size Image Generator",
    slug: "passport-size-image-generator",
    description: "Prepare portrait photos in passport-size formats.",
    category: "Image Tools",
    icon: "🪪",
  },
  {
    name: "Merge PDF",
    slug: "merge-pdf",
    description: "Combine multiple PDFs into one file.",
    category: "Document Tools",
    icon: "🔗",
  },
  {
    name: "PDF Compressor",
    slug: "pdf-compressor",
    description: "Compress PDF files to reduce size while preserving quality.",
    category: "Document Tools",
    icon: "🔥",
  },
  {
    name: "Split PDF",
    slug: "split-pdf",
    description: "Split PDF into separate pages.",
    category: "Document Tools",
    icon: "✂️",
  },
  {
    name: "Rotate PDF",
    slug: "rotate-pdf",
    description: "Rotate PDF pages.",
    category: "Document Tools",
    icon: "🔃",
  },
  {
    name: "Organize PDF",
    slug: "organize-pdf",
    description: "Reorder, rotate, delete and organize PDF pages easily.",
    category: "Document Tools",
    icon: "📑",
  },
  {
    name: "Add Watermark to PDF",
    slug: "add-watermark-to-pdf",
    description: "Stamp text or image watermarks onto PDF pages.",
    category: "Document Tools",
    icon: "💧",
  },
  {
    name: "Remove Pages from PDF",
    slug: "remove-pages-from-pdf",
    description: "Delete selected pages from a PDF document.",
    category: "Document Tools",
    icon: "❌",
  },
  {
    name: "Extract Images from PDF",
    slug: "extract-images-from-pdf",
    description: "Extract embedded images from PDF files.",
    category: "Document Tools",
    icon: "🖼️",
  },
  {
    name: "PDF to Images",
    slug: "pdf-to-images",
    description: "Convert PDF pages into JPG or PNG images.",
    category: "Document Tools",
    icon: "🖼️",
  },
  {
    name: "Add Page Numbers",
    slug: "add-page-numbers",
    description: "Insert page numbers into PDF documents.",
    category: "Document Tools",
    icon: "#️⃣",
  },
  {
    name: "Protect PDF",
    slug: "protect-pdf",
    description: "Add password to PDF.",
    category: "Document Tools",
    icon: "🔒",
  },
  {
    name: "Unlock PDF",
    slug: "unlock-pdf",
    description: "Remove password from PDF.",
    category: "Document Tools",
    icon: "🔓",
  },
  {
    name: "PDF to Word",
    slug: "pdf-to-word",
    description: "Convert PDF files to editable Word documents.",
    category: "Document Tools",
    icon: "📝",
  },
  {
    name: "Word to PDF",
    slug: "word-to-pdf",
    description: "Convert Word documents into PDF format.",
    category: "Document Tools",
    icon: "📄",
  },
  {
    name: "PDF to Excel",
    slug: "pdf-to-excel",
    description: "Extract tables from PDF into Excel format.",
    category: "Document Tools",
    icon: "📊",
  },
  {
    name: "Excel to PDF",
    slug: "excel-to-pdf",
    description: "Convert Excel spreadsheets into PDF files.",
    category: "Document Tools",
    icon: "📋",
  },
  {
    name: "PDF to PowerPoint",
    slug: "pdf-to-powerpoint",
    description: "Convert PDF files into PowerPoint slides.",
    category: "Document Tools",
    icon: "📽️",
  },
  {
    name: "PowerPoint to PDF",
    slug: "powerpoint-to-pdf",
    description: "Convert PowerPoint presentations into PDF.",
    category: "Document Tools",
    icon: "🎯",
  },
  {
    name: "PDF to TXT",
    slug: "pdf-to-txt",
    description: "Extract text from PDF files.",
    category: "Document Tools",
    icon: "📃",
  },
  {
    name: "TXT to PDF",
    slug: "txt-to-pdf",
    description: "Convert plain text files into PDF format.",
    category: "Document Tools",
    icon: "📄",
  },
  {
    name: "Word to HTML",
    slug: "word-to-html",
    description: "Convert Word documents into HTML code.",
    category: "Document Tools",
    icon: "🌐",
  },
  {
    name: "Video to MP3",
    slug: "video-to-mp3",
    description: "Extract MP3 audio from uploaded video files.",
    category: "Video Tools",
    icon: "🎧",
  },
  {
    name: "Video Compressor",
    slug: "video-compressor",
    description: "Reduce video file size for faster sharing and upload.",
    category: "Video Tools",
    icon: "🎞️",
  },
  {
    name: "Video Cutter",
    slug: "video-cutter",
    description: "Trim video clips to keep only the section you need.",
    category: "Video Tools",
    icon: "✂️",
  },
  {
    name: "Thumbnail Downloader (YouTube)",
    slug: "thumbnail-downloader-youtube",
    description: "Fetch and download YouTube video thumbnails in common sizes.",
    category: "Video Tools",
    icon: "🖼️",
  },
  {
    name: "JSON Formatter",
    slug: "json-formatter",
    description: "Beautify and format JSON.",
    category: "Developer Tools",
    icon: "🛠️",
  },
  {
    name: "QR Generator",
    slug: "qr-generator",
    description: "Generate QR code instantly.",
    category: "Developer Tools",
    icon: "⬛",
  },
  {
    name: "Base64 Tool",
    slug: "base64-tool",
    description: "Encode and decode Base64.",
    category: "Developer Tools",
    icon: "🔐",
  },
  {
    name: "HTML Formatter",
    slug: "html-formatter",
    description: "Format raw HTML into a readable structure.",
    category: "Developer Tools",
    icon: "🧱",
  },
  {
    name: "CSS Formatter",
    slug: "css-formatter",
    description: "Beautify packed CSS into clean readable code.",
    category: "Developer Tools",
    icon: "🎨",
  },
  {
    name: "JS Formatter",
    slug: "js-formatter",
    description: "Format JavaScript code with cleaner line breaks.",
    category: "Developer Tools",
    icon: "⚙️",
  },
  {
    name: "SQL Formatter",
    slug: "sql-formatter",
    description: "Format SQL queries into readable clauses.",
    category: "Developer Tools",
    icon: "🗃️",
  },
  {
    name: "JWT Decoder",
    slug: "jwt-decoder",
    description: "Decode JWT header and payload locally.",
    category: "Developer Tools",
    icon: "🔍",
  },
  {
    name: "URL Parser",
    slug: "url-parser",
    description: "Parse URLs into path, query, and hash parts.",
    category: "Developer Tools",
    icon: "🔗",
  },
  {
    name: "Regex Tester",
    slug: "regex-tester",
    description: "Test regular expressions against sample text.",
    category: "Developer Tools",
    icon: "🧪",
  },
  {
    name: "Timestamp Converter",
    slug: "timestamp-converter",
    description: "Convert timestamps into dates and back again.",
    category: "Developer Tools",
    icon: "⏱️",
  },
  {
    name: "GST Calculator",
    slug: "gst-calculator",
    description: "Calculate GST easily.",
    category: "Calculators",
    icon: "💰",
  },
  {
    name: "EMI Calculator",
    slug: "emi-calculator",
    description: "Calculate EMI quickly.",
    category: "Calculators",
    icon: "🏦",
  },
  {
    name: "Age Calculator",
    slug: "age-calculator",
    description: "Calculate your age.",
    category: "Calculators",
    icon: "🎂",
  },
  {
    name: "Percentage Calculator",
    slug: "percentage-calculator",
    description: "Calculate percentage instantly.",
    category: "Calculators",
    icon: "📊",
  },
  {
    name: "SIP Calculator",
    slug: "sip-calculator",
    description: "Calculate SIP investment growth.",
    category: "Calculators",
    icon: "📈",
  },
  {
    name: "FD Calculator",
    slug: "fd-calculator",
    description: "Estimate fixed deposit maturity value and total interest earned.",
    category: "Calculators",
    icon: "🏛️",
  },
  {
    name: "RD Calculator",
    slug: "rd-calculator",
    description: "Calculate recurring deposit maturity from monthly contributions.",
    category: "Calculators",
    icon: "🪙",
  },
  {
    name: "Loan EMI Breakdown Calculator",
    slug: "loan-emi-breakdown-calculator",
    description: "See EMI, total interest, repayment, and principal-interest split.",
    category: "Calculators",
    icon: "📑",
  },
  {
    name: "Simple Interest Calculator",
    slug: "simple-interest-calculator",
    description: "Calculate simple interest and total payable amount.",
    category: "Calculators",
    icon: "➕",
  },
  {
    name: "Compound Interest Calculator",
    slug: "compound-interest-calculator",
    description: "Estimate future value using compound interest.",
    category: "Calculators",
    icon: "🧮",
  },
  {
    name: "Inflation Calculator",
    slug: "inflation-calculator",
    description: "Understand future cost and purchasing power after inflation.",
    category: "Calculators",
    icon: "📉",
  },
  {
    name: "Income Tax Calculator",
    slug: "income-tax-calculator",
    description: "Quickly estimate annual income tax and effective tax rate.",
    category: "Calculators",
    icon: "🧾",
  },
  {
    name: "Salary / In-hand Calculator",
    slug: "salary-in-hand-calculator",
    description: "Estimate monthly in-hand salary after PF and tax assumptions.",
    category: "Calculators",
    icon: "💼",
  },
  {
    name: "Keyword Density Checker",
    slug: "keyword-density-checker",
    description: "Check keyword frequency and density from pasted content.",
    category: "SEO Tools",
    icon: "🔎",
  },
  {
    name: "Meta Tag Generator",
    slug: "meta-tag-generator",
    description: "Generate HTML meta tags for titles, descriptions, canonicals, and robots.",
    category: "SEO Tools",
    icon: "🏷️",
  },
  {
    name: "Sitemap Generator",
    slug: "sitemap-generator",
    description: "Create XML sitemaps from a list of page URLs.",
    category: "SEO Tools",
    icon: "🗺️",
  },
  {
    name: "Robots.txt Generator",
    slug: "robots-txt-generator",
    description: "Generate a valid robots.txt file with allow, disallow, and sitemap rules.",
    category: "SEO Tools",
    icon: "🤖",
  },
  {
    name: "OG Generator",
    slug: "og-generator",
    description: "Create Open Graph and Twitter card tags for social previews.",
    category: "SEO Tools",
    icon: "🧩",
  },
  {
    name: "CGPA to Percentage Calculator",
    slug: "cgpa-to-percentage-calculator",
    description: "Convert CGPA into percentage using a configurable factor.",
    category: "Calculators",
    icon: "🎓",
  },
  {
    name: "Percentage to CGPA Calculator",
    slug: "percentage-to-cgpa-calculator",
    description: "Convert percentage marks into CGPA.",
    category: "Calculators",
    icon: "📚",
  },
];

export const getToolBySlug = (slug: string) =>
  tools.find((tool) => tool.slug === slug);

export const categories = [...new Set(tools.map((tool) => tool.category))];
